version: '3'
services:
  user-mongodb:
    image: mongo:latest
    container_name: user-mongodb
    ports:
      - "27017:27017"
    volumes:
      - user-mongodb-data:/data/db

  event-mongodb:
    image: mongo:latest
    container_name: event-mongodb
    ports:
      - "27018:27017"
    volumes:
      - event-mongodb-data:/data/db

  registration-mongodb:
    image: mongo:latest
    container_name: registration-mongodb
    ports:
      - "27019:27017"
    volumes:
      - registration-mongodb-data:/data/db

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    depends_on:
      - user-mongodb

  event-service:
    build:
      context: .
      dockerfile: services/event-service/Dockerfile
    depends_on:
      - event-mongodb

  registration-service:
    build:
      context: .
      dockerfile: services/registration-service/Dockerfile
    depends_on:
      - registration-mongodb

  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - event-service
      - registration-service

volumes:
  user-mongodb-data:
  event-mongodb-data:
  registration-mongodb-data:
