version: '3'
services:
  user-mongodb:
    image: mongo:latest
    container_name: user-mongodb
    ports:
      - "27017:27017"
    volumes:
      - user-mongodb-data:/data/db
    networks:
      - user-network

  event-mongodb:
    image: mongo:latest
    container_name: event-mongodb
    ports:
      - "27018:27017"
    volumes:
      - event-mongodb-data:/data/db
    networks:
      - event-network

  registration-mongodb:
    image: mongo:latest
    container_name: registration-mongodb
    ports:
      - "27019:27017"
    volumes:
      - registration-mongodb-data:/data/db
    networks:
      - registration-network

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    depends_on:
      - user-mongodb
    networks:
      - user-network

  event-service:
    build:
      context: .
      dockerfile: services/event-service/Dockerfile
    depends_on:
      - event-mongodb
    networks:
      - event-network

  registration-service:
    build:
      context: .
      dockerfile: services/registration-service/Dockerfile
    depends_on:
      - registration-mongodb
    networks:
      - registration-network

  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - event-service
      - registration-service
    networks:
      - user-network
      - event-network
      - registration-network

volumes:
  user-mongodb-data:
  event-mongodb-data:
  registration-mongodb-data:

networks:
  user-network:
  event-network:
  registration-network:
