version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    depends_on:
      - mongodb

  event-service:
    build:
      context: .
      dockerfile: services/event-service/Dockerfile
    depends_on:
      - mongodb

  registration-service:
    build:
      context: .
      dockerfile: services/registration-service/Dockerfile
    depends_on:
      - mongodb

  nginx:
    image: nginx:latest
    ports:
      - "8090:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - event-service
      - registration-service

volumes:
  mongo_data:
